data_fetching:
  base_url: "https://api.themoviedb.org/3"
  search_endpoint: "/discover/movie"
  total_pages: 50
  save_file: "artifacts/raw/movies_1000.json"
  CSV_data_path: "artifacts/CSV_data.csv"
